### ISSUE TITLE
Collapse symbols not displaying anymore

### ISSUE THREAD

**Issue by flipchart** [niyazpk/Collapsible-comments-for-Hacker-News#1]
HN has recently changed their HTML, and as a result, the collapse symbols are not displaying anymore

See also [this comment](https://addons.mozilla.org/en-US/firefox/addon/hn-utility-suite/reviews/536906/)

**Comment by theoretick** [comment]
I guess this is no longer the case? Seems to work fine in Chrome (OSX 41.0.2272.118 (64-bit))

**Comment by niyazpk** [comment]
This is still working for me.

Can you please try again and let me know if this is still an issue? Also, kindly add a link to the page where this is not working as expected. Thanks!

**Comment by flipchart** [comment]
@theoretick Yeah, this was an issue ages ago (note the date), and resolved itself within a few days - I imagine they made another change which meant the plugin worked again
